export default {
  boards: {
    'janfred': {
      users: ['Jan', 'Fred'],
      balance: 1000,
      debts: [{
        user: 0,
        gets: 100,
        reason: 'Spagheten, Pesto, Kaffee'
      }, {
        user: 0,
        gets: 101,
        reason: 'Müllbeutel'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }, {
        user: 1,
        gets: 1,
        reason: 'Kackpappe'
      }]
    }
  }
}
